[package]
name = "gitalky"
version = "0.1.0"
edition = "2024"
rust-version = "1.90"

[dependencies]
# Phase 1
thiserror = "1.0"

# Phase 2
ratatui = "0.28"
crossterm = "0.28"

[dev-dependencies]
tempfile = "3.0"  # For test git repositories
